// ADD ITEMS TO CART
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

// DELETE CART INFO IN LOCAL STORAGE AFTER ORDER PLACED
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

// LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// LOGOUT
export const USER_LOGOUT = "USER_LOGOUT";

// REGISTER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";

// PAGE_SIZE
export const PAGE_SIZE = 10;
